version: '3.8'

services:
  app:
    container_name: instant-mqtt-relay-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "9001:9001"
    depends_on:
      - broker
    networks:
      - instant-mqtt-relay

  broker:
    container_name: instant-mqtt-relay-broker
    image: eclipse-mosquitto
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - instant-mqtt-relay
    restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-config:
  mosquitto-log:

networks:
  instant-mqtt-relay:
    driver: bridge
  instant-mqtt-relay-host:
    external: true